### ISSUE TITLE
Add File fields for EQ model

### ISSUE THREAD

**Issue by Jannes123** [AIFDR/inasafe-django#52]
The web push will include a pdf and png file which needs to be accomodated in the django model.  

We need to add these two fields in the model.

**Comment by Jannes123** [comment]
subtask of #47

**Comment by lucernae** [comment]
Since the report files can be for many languages for one shake id, I decided to split the model using One-to-Many relationships.

Now, we had two models:
- Earthquake: store shake id, magnitude, location, location description, and depth
- Earthquake report: store language id, report pdf, report image, report thumbnail for a certain shake id
